### ISSUE TITLE
add more error messages

### ISSUE THREAD

**Issue by massachusett** [cytomining/DeepProfiler#105]

**Comment by massachusett** [comment]
parameter checking

**Comment by massachusett** [comment]
include checking if file structure is formatted correctly

**Comment by massachusett** [comment]
also clean up what is printed on the terminal; it should be very readable

**Comment by massachusett** [comment]
check if compression has been run

**Comment by jccaicedo** [comment]
The json schema can help solving part of this issue #157

**Comment by jccaicedo** [comment]
Closing for now.
