### ISSUE TITLE
DeepProfiler - test run on GPU

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#182]
@jccaicedo 
DeepProfiler did not use GPU for me.
I am going to try `CUDA_VISIBLE_DEVICES` ahead.

**Comment by jccaicedo** [comment]
@Arkkienkeli I think you fixed this recently, right?
Can you confirm and close pointing to the commit hash here?

**Comment by Arkkienkeli** [comment]
Closed with \0a4fdfe4ca22f59ee5d7c19c3b7ce078df78e1e7

**Comment by Arkkienkeli** [comment]
@jccaicedo Training does not work for me.
