### ISSUE TITLE
DenseNet update + test

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#214]
Update DenseNet in the project and add the test for it. 
Test it with the bbbc021 dataset.

**Comment by jccaicedo** [comment]
Experiments run by @Arkkienkeli with the proposed code:
https://www.comet.ml/jccaicedo/bbbc021/5a0258fc8f14450f9bd08e78894aee42

**Comment by Arkkienkeli** [comment]
Done 794ac68609e18cd440cf18114b888b8ff4c9d9eb
