### ISSUE TITLE
Parameter for network input shape in repeat_channel_crop_generator 

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#215]

**Comment by jccaicedo** [comment]
This is useful for pretrained networks

**Comment by jccaicedo** [comment]
For instance, InceptionResNetV2 has 299x299 input size, but EfficientNetB0 is 224x224.

**Comment by Arkkienkeli** [comment]
Done 59a45f96db0b22d52b02cb42b594bc0d1e220516
