### ISSUE TITLE
Refactoring of the config and param

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#232]
- Change config parameter `queue`  to `cache`
- Rename `--cometml_key` command-line flag to `--logging`
- Update in the wiki

**Comment by jccaicedo** [comment]
Agreed. Here are my additional notes:

1. We need to change the `queue` parameter for `cache` in the configuration file, but also in the code base, variables that refer to a `queue` should refer to a `cache`. Notably in the cropping.py module, but possible in some other places.

2. After renaming the flag `--cometml_key` for `--logging`, the `JSON` file that contains the key should have another parameter specifying the type of logging: `"log_type":"comet_ml"`. The idea is that in the future we also support TensorBoard and other technologies, not just comet.ml.

**Comment by Arkkienkeli** [comment]
50b2e3110e8c8938bf2017313239cd6637781283
