### ISSUE TITLE
Compression of the dataset misses creation of the directory outputs/compressed/metadata and crashes in the end

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#242]
Compression of the dataset misses creation of the directory outputs/compressed/metadata and crashes in the end

**Comment by jccaicedo** [comment]
This has been fixed. Please link the commit or PR here, delete the branch and feel free to close.

**Comment by Arkkienkeli** [comment]
Fixed https://github.com/cytomining/DeepProfiler/pull/243
