### ISSUE TITLE
Travis CI has changed their pricing structure for open source projects

### ISSUE THREAD

**Issue by GenevieveBuckley** [cytomining/DeepProfiler#245]
Travis has just announced a change in their pricing structure, and no longer offer free builds for open source projects. https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

If those changes are incompatible with the needs of this project, it might be necessary to switch to another CI service.

**Comment by jccaicedo** [comment]
Thank you for reporting this @GenevieveBuckley . We will remove it from our project.
@Arkkienkeli , can you make this change? We want to remove Travis from our project configuration files.

**Comment by Arkkienkeli** [comment]
@jccaicedo I removed the Travis CI config from the project, but probably you also should have a look at repository settings if anything left related to Travis. I don't have access to it.

**Comment by Arkkienkeli** [comment]
@jccaicedo I guess we can close it?

**Comment by jccaicedo** [comment]
Yes! Thanks for making the update. Closing now.
