### ISSUE TITLE
Metadata parameter for command line and get rid of compressed.csv

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#250]
We have separate metadata for compressed images now which is not truly necessary. 
Instead, we will change paths on the fly by checking the usage of compressed images in the config.
Also, by the `--metadata` option user will be able to choose the metadata file from `inputs/metadata` for better user-experience in sophisticated experiments. Default would be `index.csv` (as it is now).

**Comment by jccaicedo** [comment]
The following commit added the features: 1743c56851a4114b7143f07966a5672f83452432
