### ISSUE TITLE
Save crops and profiles in folder structure

### ISSUE THREAD

**Issue by michaelbornholdt** [cytomining/DeepProfiler#264]
There are some arguements why to save profile npz files and cropped png images in a folder structure :
- folders have limitations on the number of files withing them
- large folders slow down commands and give a bad overview

This is why I will try and change to the following structure for profile outputs: 

```
├── Plate1
│   ├── A01
│   |   ├── Site1.npz
│   |   └── Site2.npz
│   └── A02
│   |   ├── Site1.npz
│   |   └── Site2.npz
```

The cropped single cell images should look like this: 
```
├── Plate1
│   ├── A01
│   |   ├── Site1
│   │   |   ├── Img1.png
│   │   |   └── Img2.png
```

**Comment by michaelbornholdt** [comment]
PR: https://github.com/cytomining/DeepProfiler/pull/265

**Comment by jccaicedo** [comment]
This new structure has been adopted with the following commits:
e1824b6a6a4f75fb36466fbd6d85cf1e20044bf0
d0cce7f87ffaf674b7d00ae4e6ff07229550f7d7
e1824b6a6a4f75fb36466fbd6d85cf1e20044bf0

Thanks for the PR, @michaelbornholdt !

I'm going to close this issue for now, but if you have any trouble with this going forward, feel free to report.
