### ISSUE TITLE
Number of steps is invariant to the crop generator (and samples). 

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#272]
DeepProfiler computes the number of steps for `model.fit` with use of location files and then sampling and balancing it. 
https://github.com/cytomining/DeepProfiler/blob/tf2/deepprofiler/dataset/image_dataset.py#L99

The problem is that in the case of `sampled_crop_generator` it should be calculated differently and the sampled set is supposed to be already balanced.

**Comment by michaelbornholdt** [comment]
@jccaicedo @Arkkienkeli 
So here we discuss how to fix error #271.

**Comment by michaelbornholdt** [comment]
Nikita suggested this on line 

https://github.com/cytomining/DeepProfiler/blob/tf2/deepprofiler/dataset/image_dataset.py#L99

`self.steps_per_epoch = int((len(os.listdir(SAMPLE_DIR)) - 1) / batch_size)`

**Comment by michaelbornholdt** [comment]
@Arkkienkeli Any idea how to get SAMPLE_DIR. I always am confused of which dict holds the location of sample sc...

**Comment by Arkkienkeli** [comment]
@michaelbornholdt It should be in `config['paths']['single_cell_sample']`
https://github.com/cytomining/DeepProfiler/blob/d92b94fdea59a289bfff38e4962cc8cf3bec15f7/deepprofiler/__main__.py#L59

**Comment by Arkkienkeli** [comment]
Fixed in https://github.com/cytomining/DeepProfiler/commit/6f05e2e826c0d95961a2097dff8b09c8707b68f9
