### ISSUE TITLE
Merge tf2 and new_tf2_training branches into single branch

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#273]
We need to merge branches [tf2](https://github.com/cytomining/DeepProfiler/tree/tf2) and [new_tf2_training](https://github.com/cytomining/DeepProfiler/tree/new_tf2_training).
[tf2](https://github.com/cytomining/DeepProfiler/tree/tf2) contains the current stable version of DeepProfiler with all functionality, it runs with TF2, but with the code was re-used from TF1 version of DeepProfiler. 
We want to add a training from [new_tf2_training](https://github.com/cytomining/DeepProfiler/tree/new_tf2_training) which uses TF2 eager execution and datasets, so it will be a separate training command.

**Comment by jccaicedo** [comment]
Seems like the code in `new_tf2_training` has been already added to the `tf2` branch. @Arkkienkeli can you please double check, and if so, remove the `new_tf2_training` branch and close this issue.

**Comment by Arkkienkeli** [comment]
The `new_tf2_training` branch does not seem to contain the code to merge. The branch will be removed.
