### ISSUE TITLE
Synchronize master and tf2 branches

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#274]
We need to have a look which latest commits we can incorporate to [tf2](https://github.com/cytomining/DeepProfiler/tree/tf2) branch from the master branch.

**Comment by jccaicedo** [comment]
The two branches have been merged. We need to test whether code is still functional. @Arkkienkeli can you please check this?

**Comment by Arkkienkeli** [comment]
Done with 69b9272a0dec8b12c6f29a7339dfbf71b9a17d63
