### ISSUE TITLE
Integrate sample_crop_generator into traintf2

### ISSUE THREAD

**Issue by jccaicedo** [cytomining/DeepProfiler#297]
Extend the dataset functionality of TFv2 with our crop generator based on pre-cropped single cells.

Pre-cropped single cells will be the official mode for training going forward. This crop generator has class balancing and other on-the-fly functionalities that are nice to have during training. By integrating this crop generator in traintf2, we would be ready to merge with master.

**Comment by Arkkienkeli** [comment]
Closed #307
