### ISSUE TITLE
Do not break training with zero crop

### ISSUE THREAD

**Issue by michaelbornholdt** [cytomining/DeepProfiler#298]
I will need to dig up the actual error but we know that black crops create a div by 0 errro and thus the loss function becomes NaN. 

This is a breaking error and can only be solved by running my zero helper functions after sampling data. 

To me, this seems like a rather easy and important fix. 
@jccaicedo

**Comment by jccaicedo** [comment]
I agree @michaelbornholdt , it should be easy.
Where do you suggest to fix it, during cropping or during training? I think @Arkkienkeli also mentioned this recently to me. Any suggestions on how to proceed to fix this?
