### ISSUE TITLE
Refactor and clean up learning

### ISSUE THREAD

**Issue by jccaicedo** [cytomining/DeepProfiler#311]
As we remove TFv1 from the code base, we can simplify the training logic.
Keep only one training command going forward.

**Comment by jccaicedo** [comment]
Drop model.py and rename tf2train.py to model.py as well.

**Comment by jccaicedo** [comment]
Remove the model factory in the model plugins (EfficientNet and ResNet).

**Comment by jccaicedo** [comment]
From the metric plugins, remove top_k.py and make sure that we adopt the native TFv2 version of it.

**Comment by Arkkienkeli** [comment]
Closed #312
