### ISSUE TITLE
Formalize Docker images

### ISSUE THREAD

**Issue by michaelbornholdt** [cytomining/DeepProfiler#314]
Re Juans comment about the Docker images. 
here is the Dockerfile that I would propose to use. 
Feel free to add anything in the comments and then I can make a PR. 

```
# import tensorflow GPU docker image
FROM tensorflow/tensorflow:2.5.1-gpu

# update installing scripts
RUN /usr/bin/python3 -m pip install --upgrade pip
RUN apt-get update
RUN apt update

# install usefull tools
RUN apt-get -y install nano
RUN apt install -y tmux
RUN apt install -y htop
RUN apt install -y git

# install open cv
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt install libgl1-mesa-glx -y
RUN pip install opencv-python

# install DeepProfiler
RUN git clone https://github.com/cytomining/DeepProfiler.git
WORKDIR DeepProfiler
RUN pip install -e .

# install Pycytominer and eval
RUN pip install git+git://github.com/cytomining/pycytominer
RUN pip install cytominer-eval



```

**Comment by michaelbornholdt** [comment]
@jccaicedo @Arkkienkeli

**Comment by jccaicedo** [comment]
This looks good, @michaelbornholdt ! 

This is the script you used to run your experiments, right? According to our last conversation, we will create a separate repository for this. I will create it and will tag you there so you can create the PR there.

**Comment by jccaicedo** [comment]
I just invited @michaelbornholdt and @Arkkienkeli to the new repository, and have tagged you to submit the dockerfile there.

I'm closing this issue for now.
