### ISSUE TITLE
Validation - all data in RAM

### ISSUE THREAD

**Issue by Arkkienkeli** [cytomining/DeepProfiler#324]
Currently all validation data is loaded to RAM, replace it with loading on-the-fly.

**Comment by Neovan1** [comment]
I'm facing this issue as well. All of the validation data is getting loaded into the instance RAM and not being released. Tried changing the instance type to a memory intensive one and it doesn't seem to help as well. Does any one know if this can be optimized within the application itself.

Appreciate any help on this !

**Comment by Arkkienkeli** [comment]
Fixed in https://github.com/cytomining/DeepProfiler/pull/328.
