### ISSUE TITLE
Matching channel to respective 1280 features from DeepProfiler

### ISSUE THREAD

**Issue by jenna-tomkinson** [cytomining/DeepProfiler#329]
Hello,

I am currently using DeepProfiler with [a project] (https://github.com/WayScience/NF1_SchwannCell_data) where I am extracting features from Cell Painting data with three channels (DAPI, GFP, RFP). Specifically, my goal is to use center (x,y) coordinates from segmented nuclei and cytoplasm using Cellpose to extract the features from. I am using the [pretrained model](https://github.com/broadinstitute/luad-cell-painting/tree/main/outputs/efn_pretrained/checkpoint) from the [LUAD Cell Painting repository](https://github.com/broadinstitute/luad-cell-painting), which @roshankern and I have used in projects within the @gwaybio lab. 

Since my project will have 3840 features, I was wondering if there is anyway to know which of the groups of 1280 features corresponded to a specific channel for downstream analysis purposes. Is it safe to assume that features 1 through 1,280 are from the first channel, and so on?

Thank you in advance for your assistance with this!

Jenna

**Comment by jccaicedo** [comment]
Hi Jenna,

Yes, the assumption that you are making is correct. The order of the channels that you assign in the JSON configuration file should be the same order of the features in the output vector. Tagging @Arkkienkeli in case there is another consideration to make.

I hope this helps!

Juan C.

**Comment by Arkkienkeli** [comment]
@jccaicedo Is totally correct here, the order of features for pre-trained networks used with `repeat_channel_crop_generator` is the same as in the `channels` field of configuration.
I have also updated the profiling notebook with the description of how it works. 
Closing now.
