### ISSUE TITLE
Error extracting example data

### ISSUE THREAD

**Issue by binghama** [cytomining/DeepProfiler#340]
After cloning the repository, I ran the following to extract the data as recommended:

`tar -xzf example_data.tar.gz`

However I received the following error:

`gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
`

Any guidance on this? Thanks!

**Comment by Arkkienkeli** [comment]
Hi @binghama, was the file fully cloned and if not, is `git-lfs` installed? 
The cloned archive should be about ~150 MB.

**Comment by binghama** [comment]
Thank you @Arkkienkeli, I do not have git-lfs installed so I guess that is the issue.
