### ISSUE TITLE
Example data download - This repository is over its data quota

### ISSUE THREAD

**Issue by binghama** [cytomining/DeepProfiler#341]
I tried to clone the repository and was not able to download the sample data due to the following error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/80488082/196552972-5e6ca8ab-2658-4878-9f40-86918e45f1ec.png)

It says that "This repository is over its data quota". I do have git-lfs installed, what is the problem here?

Thanks.

**Comment by Arkkienkeli** [comment]
Uff. Looks like we need to move example data on zenodo or somewhere else. 
Please use the Google Drive link as a temporal solution: [link].(https://drive.google.com/file/d/1W0IIZ2FEqKR_3tZk6yISOjZVoYa0NTqM/view?usp=sharing)
Thank you for reporting, please keep the issue open for now, we will close it when we move example data.

**Comment by binghama** [comment]
Thank you @Arkkienkeli !

**Comment by Arkkienkeli** [comment]
Now the example data is [published on Zenodo](https://doi.org/10.5281/zenodo.7515132).
