### ISSUE TITLE
About feature extraction from block6a-activation layer

### ISSUE THREAD

**Issue by chenzhao2016** [cytomining/DeepProfiler#342]
hi @Arkkienkeli , it says "The size of the feature vectors is 672 for reported results, which were extracted from EfficientNet’s block6a-activation layer" in the paper. 

In EfficientNet, output shape of layer "block6a_activation" is (None, 7, 7, 672). I see the feature size is 672. Was that extracted from layer "block6a_se_squeeze" (size: None,672)? 

I am new to the field and trying to learn how to extra features...Thank you!

**Comment by jccaicedo** [comment]
No, it was not extracted from `block6a_se_squeeze`. It is taken from `block6a_activation` and then we use average pooling over the spatial dimensions. We will clarify this in the paper and the documentation.

Thanks for your feedback!

**Comment by chenzhao2016** [comment]
Thank you very much for the clarification @jccaicedo !!  Would you mind sharing how the average pooling over the spatial dimensions was performed? We should be to follow it if you could kindly point it out in the DeepProfiler code.

**Comment by Arkkienkeli** [comment]
Hello @chenzhao2016, the part with the spatial pooling in DeepProfiler can be found [here](https://github.com/cytomining/DeepProfiler/blob/master/deepprofiler/learning/profiling.py#L91).

**Comment by chenzhao2016** [comment]
Thank you so much @Arkkienkeli !! This is super helpful!
