### ISSUE TITLE
Is image crops size box_size or use_pretrained_input_size when profiling with ImageNet pre-trained model?

### ISSUE THREAD

**Issue by gzzwjhzxh** [cytomining/DeepProfiler#351]
Dear developer, my image size is 2048×2048 and I want to use the pre-trained effnet model to profile the images. 
I found two parameters in the configuration file: box_size and use_pretrained_input_size. I want to know if box_size=448 and
use_pretrained_input_size=224, when cropping the single cell region from the image, does it crop with box_size and 
then resize to use_pretrained_input_size for profiling, or does it crop directly with use_pretrained_input_size and then profiling?
        Looking forward to your reply, thank you very much!

**Comment by Arkkienkeli** [comment]
Hello, yes, the initial crops would be `box_size` and then resized to `224`. We do that to fit inputs of pretrained (on ImageNet) model.

**Comment by gzzwjhzxh** [comment]
Thank you very much for your reply, so I can set the box_size according to my needs.

**Comment by gzzwjhzxh** [comment]
Please allow me to ask you another question, if I only have two-channel images, and I want to use the pre-trained Cell Painting CNN model to profile them, do you suggest using the repeat channel method to expand the single channel to five channels to fit the input of the Cell Painting CNN model?

**Comment by Arkkienkeli** [comment]
> Please allow me to ask you another question, if I only have two-channel images, and I want to use the pre-trained Cell Painting CNN model to profile them, do you suggest using the repeat channel method to expand the single channel to five channels to fit the input of the Cell Painting CNN model?

You can try this.

Also, please note that my previous reply was about ImageNet pretrained model, not Cell Painting CNN !

**Comment by gzzwjhzxh** [comment]
Thank you very much. I understand that the repeat channel method may need to be changed for the Cell Painting CNN model.
