### ISSUE TITLE
Cannot Download example data 

### ISSUE THREAD

**Issue by philippschw** [cytomining/DeepProfiler#356]
When I clone the repository, I get an Error downloading example_data.tar.gz. It says that the repository is over its data quota. `Account responsible for LFS bandwidth should purchase more data packs to restore access.`

I feel the example data is very useful to quickly explore the repo and also for adapting it to private data. Could you fix this issue or make the data available on another fileshare? 

Thanks!

**Comment by Arkkienkeli** [comment]
Hello @philippschw , you can download it from Zenodo. 
https://doi.org/10.5281/zenodo.7515132 (the link is also available in the ReadMe of the repository).
